# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Chun
tagline:          'A Jekyll theme'
description:      'Never Stop Learning'
url:              https://blog.chunsann.com
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Chun Tsai'
  url:            https://twitter.com/chunntsai

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            
sidebar_home_link:  true
github:
  repo:             https://github.com/fongandrew/hydeout

disqus.shortname: oukalatte
