# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Guang
tagline:          'Blog'
description:      '請你退出競爭行列'
url:              https://dorisloveguang.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Guang'
  url:            https://dorisloveguang.github.io

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
#version:            
sidebar_home_link:  true
github:
  repo:             https://github.com/dorisloveguang

